name: Inject Firebase Secrets and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🛠️ Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: 🔐 Inject Firebase config using envsubst
        run: |
          envsubst < public/JS/firebase-config.template.js > public/JS/firebase-config.js
        env:
          APIKEY: ${{ secrets.APIKEY }}
          AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          PROJECTID: ${{ secrets.PROJECTID }}
          STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
          MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
          APPID: ${{ secrets.APPID }}

      - name: 🚀 Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
